services:
  db:
    image: postgres:15
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    build: .
    container_name: weather_migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: alembic upgrade head
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MODEL_PATH: /models
      RETRAIN_HOUR: ${ML_RETRAIN_HOUR:-2}
      RETRAIN_MINUTE: ${ML_RETRAIN_MINUTE:-0}
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      ML_SERVICE_URL: http://localhost:8001
    volumes:
      - .:/app
      - ml_models:/app/models
    ports:
      - "8000:8000"
      - "8001:8001"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: app/frontend-app
      dockerfile: Dockerfile
    container_name: weather_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - app
    environment:
      - VITE_API_URL=http://app:8000
      - VITE_PORT=5173
    volumes:
      - ./app/frontend-app:/app
      - /app/node_modules

  cron:
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    container_name: cron_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

volumes:
  postgres_data:
  ml_models:
