"""fix city ref in weather_daily

Revision ID: 028986b8256e
Revises: adf9d8876a58
Create Date: 2026-05-11 21:28:06.654502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "028986b8256e"
down_revision: Union[str, Sequence[str], None] = "adf9d8876a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("weather_daily_city_id_fkey"), "weather_daily", type_="foreignkey"
    )
    op.rename_table("cities", "city")
    # op.create_table(
    #     "city",
    #     sa.Column("id", sa.Integer(), nullable=False),
    #     sa.Column("name", sa.String(), nullable=False),
    #     sa.Column("latitude", sa.Float(), nullable=False),
    #     sa.Column("longitude", sa.Float(), nullable=False),
    #     sa.PrimaryKeyConstraint("id"),
    #     sa.UniqueConstraint("name"),
    # )
    # op.drop_table("cities")
    op.create_foreign_key(None, "weather_daily", "city", ["city_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weather_daily", type_="foreignkey")
    op.create_foreign_key(
        op.f("weather_daily_city_id_fkey"),
        "weather_daily",
        "cities",
        ["city_id"],
        ["id"],
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cities_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("cities_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("city")
    # ### end Alembic commands ###
