"""full openmeteo model

Revision ID: 12e13727f62d
Revises:
Create Date: 2026-05-04 22:43:06.854933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "12e13727f62d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("temperature_2m_mean", sa.Float(), nullable=True),
        sa.Column("temperature_2m_min", sa.Float(), nullable=True),
        sa.Column("temperature_2m_max", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_mean", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_min", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_max", sa.Float(), nullable=True),
        sa.Column("precipitation_sum", sa.Float(), nullable=True),
        sa.Column("rain_sum", sa.Float(), nullable=True),
        sa.Column("snowfall_sum", sa.Float(), nullable=True),
        sa.Column("precipitation_hours", sa.Float(), nullable=True),
        sa.Column("pressure_msl_mean", sa.Float(), nullable=True),
        sa.Column("relative_humidity_2m_mean", sa.Float(), nullable=True),
        sa.Column("wind_speed_10m_max", sa.Float(), nullable=True),
        sa.Column("wind_gusts_10m_max", sa.Float(), nullable=True),
        sa.Column("shortwave_radiation_sum", sa.Float(), nullable=True),
        sa.Column("sunshine_duration", sa.Float(), nullable=True),
        sa.Column("uv_index_max", sa.Float(), nullable=True),
        sa.Column("daylight_duration", sa.Float(), nullable=True),
        sa.Column("weather_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weather_city_date", "weather_daily", ["city", "date"], unique=False
    )
    op.create_index(
        op.f("ix_weather_daily_city"), "weather_daily", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_weather_daily_date"), "weather_daily", ["date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_daily_date"), table_name="weather_daily")
    op.drop_index(op.f("ix_weather_daily_city"), table_name="weather_daily")
    op.drop_index("ix_weather_city_date", table_name="weather_daily")
    op.drop_table("weather_daily")
    # ### end Alembic commands ###
