"""add city model and reference to it in weather_daily

Revision ID: adf9d8876a58
Revises: 12e13727f62d
Create Date: 2026-05-06 13:39:22.316798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adf9d8876a58"
down_revision: Union[str, Sequence[str], None] = "12e13727f62d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("weather_daily", sa.Column("city_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_weather_daily_city"), table_name="weather_daily")
    op.drop_index(op.f("ix_weather_city_date"), table_name="weather_daily")
    op.create_index(
        "ix_weather_city_date", "weather_daily", ["city_id", "date"], unique=False
    )
    op.create_foreign_key(None, "weather_daily", "cities", ["city_id"], ["id"])
    op.drop_column("weather_daily", "city")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather_daily",
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "weather_daily", type_="foreignkey")
    op.drop_index("ix_weather_city_date", table_name="weather_daily")
    op.create_index(
        op.f("ix_weather_city_date"), "weather_daily", ["city", "date"], unique=False
    )
    op.create_index(
        op.f("ix_weather_daily_city"), "weather_daily", ["city"], unique=False
    )
    op.drop_column("weather_daily", "city_id")
    op.drop_table("cities")
    # ### end Alembic commands ###
